### ISSUE TITLE
Getting msg format error sox-convert

### ISSUE THREAD

**Issue by WhiteLionATX** [johanneskropf/node-red-contrib-sox-utils#1]
The sox-convert node gets a msg forwarded from "http in" node / Tasker and throws this error:
"msg with a buffer payload also needs to have a coresponding msg.format property"
The container format is mp4 and the codec is acc. As a test I saved the audio file to disk. It works and was not corrupted.

SOLVED: AMR Narrowband as codex and dormat worked.

**Comment by johanneskropf** [comment]
Hello yes the sox nodes try to guess the formats of buffer payloads when they come in. Right now they can differentiate wav, flac, aiff, ogg and mp3s. For other file formats that sox supports you will have to include the file extension (e.g dat or opus) as msg.format so that the node can pass the right information about the buffer content to sox.  Im not sure if sox supports mp4 though.
**Edit:**
I just had a look and no neither mp4 nor aac are supported formats sox. I would recommend looking at one of the ffmpeg nodes or use ffmpeg with the exec node to convert it to tge right format.

Johannes
